"""Owned temporary runtime lifecycle for generated Agent projects."""

from __future__ import annotations

import asyncio
import base64
import binascii
import codecs
import hashlib
import hmac
import importlib.util
import json
import secrets
import shutil
import socket
import subprocess
import sys
import tempfile
import threading
import time
from collections.abc import Callable, Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import quote

import httpx

from veadk.cli.generated_agent_codegen import GeneratedProject


_MAX_FILES = 300
_MAX_FILE_BYTES = 256 * 1024
_MAX_TOTAL_BYTES = 2 * 1024 * 1024
_READY_TIMEOUT_SECONDS = 30.0


def _canonical_project_bytes(project: GeneratedProject) -> bytes:
    payload = {
        "name": project.name,
        "files": sorted(
            (item.model_dump(mode="json") for item in project.files),
            key=lambda item: (str(item["path"]), str(item["content"])),
        ),
    }
    return json.dumps(
        payload,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")


class GeneratedProjectAttestor:
    """Mint short-lived proof that project source was generated by this server."""

    def __init__(
        self,
        *,
        ttl_seconds: int = 4 * 60 * 60,
        secret: bytes | None = None,
        verification_secrets: tuple[bytes, ...] = (),
        clock: Callable[[], float] | None = None,
    ) -> None:
        if ttl_seconds < 1:
            raise ValueError("ttl_seconds must be positive")
        self._ttl_seconds = ttl_seconds
        self._secret = secret or secrets.token_bytes(32)
        self._verification_secrets = (self._secret, *verification_secrets)
        self._clock = clock or time.time

    def attest(self, project: GeneratedProject, *, owner_id: str) -> str:
        expires_at = int(self._clock()) + self._ttl_seconds
        signature = self._signature(project, owner_id=owner_id, expires_at=expires_at)
        encoded = base64.urlsafe_b64encode(signature).decode("ascii").rstrip("=")
        return f"v1.{expires_at}.{encoded}"

    def verify(
        self,
        project: GeneratedProject,
        *,
        owner_id: str,
        attestation: str,
    ) -> None:
        try:
            version, raw_expiry, encoded = attestation.split(".", 2)
            expires_at = int(raw_expiry)
            padding = "=" * (-len(encoded) % 4)
            supplied = base64.urlsafe_b64decode(encoded + padding)
        except (TypeError, ValueError, binascii.Error):
            supplied = b""
            version = ""
            expires_at = 0
        if (
            version != "v1"
            or expires_at < int(self._clock())
            or not any(
                hmac.compare_digest(
                    supplied,
                    self._signature(
                        project,
                        owner_id=owner_id,
                        expires_at=expires_at,
                        secret=secret,
                    ),
                )
                for secret in self._verification_secrets
            )
        ):
            raise GeneratedAgentRuntimeError(
                422,
                "Formal evaluation requires a trusted server-generated project.",
            )

    def attest_identity(
        self,
        *,
        owner_id: str,
        agent_id: str,
        region: str,
    ) -> str:
        """Mint proof that this server checked a new Runtime identity."""

        expires_at = int(self._clock()) + self._ttl_seconds
        signature = self._identity_signature(
            owner_id=owner_id,
            agent_id=agent_id,
            region=region,
            expires_at=expires_at,
            secret=self._secret,
        )
        encoded = base64.urlsafe_b64encode(signature).decode("ascii").rstrip("=")
        return f"i1.{expires_at}.{encoded}"

    def verify_identity(
        self,
        *,
        owner_id: str,
        agent_id: str,
        region: str,
        attestation: str,
    ) -> None:
        """Verify one short-lived, owner-bound new Runtime identity proof."""

        try:
            version, raw_expiry, encoded = attestation.split(".", 2)
            expires_at = int(raw_expiry)
            padding = "=" * (-len(encoded) % 4)
            supplied = base64.urlsafe_b64decode(encoded + padding)
        except (TypeError, ValueError, binascii.Error):
            supplied = b""
            version = ""
            expires_at = 0
        if (
            version != "i1"
            or expires_at < int(self._clock())
            or not any(
                hmac.compare_digest(
                    supplied,
                    self._identity_signature(
                        owner_id=owner_id,
                        agent_id=agent_id,
                        region=region,
                        expires_at=expires_at,
                        secret=secret,
                    ),
                )
                for secret in self._verification_secrets
            )
        ):
            raise GeneratedAgentRuntimeError(
                422,
                "Formal evaluation requires a trusted Agent identity.",
            )

    def _signature(
        self,
        project: GeneratedProject,
        *,
        owner_id: str,
        expires_at: int,
        secret: bytes | None = None,
    ) -> bytes:
        message = b"\0".join(
            (
                owner_id.encode("utf-8"),
                str(expires_at).encode("ascii"),
                _canonical_project_bytes(project),
            )
        )
        return hmac.new(secret or self._secret, message, hashlib.sha256).digest()

    @staticmethod
    def _identity_signature(
        *,
        owner_id: str,
        agent_id: str,
        region: str,
        expires_at: int,
        secret: bytes,
    ) -> bytes:
        message = b"\0".join(
            (
                b"agent-identity-v1",
                owner_id.encode("utf-8"),
                agent_id.encode("utf-8"),
                region.encode("utf-8"),
                str(expires_at).encode("ascii"),
            )
        )
        return hmac.new(secret, message, hashlib.sha256).digest()


class GeneratedAgentRuntimeError(RuntimeError):
    """A safe runtime failure that can be mapped to an HTTP response."""

    def __init__(self, status_code: int, detail: str) -> None:
        super().__init__(detail)
        self.status_code = status_code
        self.detail = detail


def _free_local_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return int(sock.getsockname()[1])


@dataclass(frozen=True)
class GeneratedAgentRuntimeHandle:
    runtime_id: str
    app_name: str
    expires_at: float
    plan_hash: str = ""


@dataclass(frozen=True)
class GeneratedAgentRunEvidence:
    output: str
    trace_ref: str
    trace: tuple[dict[str, Any], ...]


@dataclass
class _RuntimeState:
    handle: GeneratedAgentRuntimeHandle
    temp_dir: str
    base_url: str
    process: subprocess.Popen[Any]
    expires_at: float
    owner_id: str


class GeneratedAgentRuntimeManager:
    def __init__(
        self,
        *,
        ttl_seconds: int,
        id_factory: Callable[[], str] | None = None,
        clock: Callable[[], float] | None = None,
        max_active_per_owner: int = 3,
        ready_timeout_seconds: float = _READY_TIMEOUT_SECONDS,
        stream_timeout_seconds: float = 600.0,
        redact: Callable[[str], str] | None = None,
    ) -> None:
        if ttl_seconds < 1:
            raise ValueError("ttl_seconds must be positive")
        if max_active_per_owner < 1:
            raise ValueError("max_active_per_owner must be positive")
        if ready_timeout_seconds <= 0:
            raise ValueError("ready_timeout_seconds must be positive")
        if stream_timeout_seconds <= 0:
            raise ValueError("stream_timeout_seconds must be positive")
        self._ttl_seconds = ttl_seconds
        self._id_factory = id_factory or (lambda: "tr_" + secrets.token_urlsafe(18))
        self._clock = clock or time.time
        self._max_active_per_owner = max_active_per_owner
        self._ready_timeout_seconds = ready_timeout_seconds
        self._stream_timeout_seconds = stream_timeout_seconds
        self._redact = redact or (lambda _: "")
        self._states: dict[str, _RuntimeState] = {}
        self._creating: dict[str, int] = {}
        self._lock = threading.Lock()

    async def create(
        self,
        project: GeneratedProject,
        *,
        environment: Mapping[str, str],
        owner_id: str,
        plan_hash: str = "",
    ) -> GeneratedAgentRuntimeHandle:
        await asyncio.to_thread(self.cleanup_expired)
        self._reserve(owner_id)
        state: _RuntimeState | None = None
        try:
            state = await asyncio.to_thread(
                self._launch,
                project,
                dict(environment),
                owner_id,
                plan_hash,
            )
            await self._wait_until_ready(state)
            with self._lock:
                if state.handle.runtime_id in self._states:
                    raise GeneratedAgentRuntimeError(
                        409,
                        "Generated Agent runtime identifier already exists.",
                    )
                self._states[state.handle.runtime_id] = state
            return state.handle
        except BaseException:
            if state is not None:
                await asyncio.to_thread(self._terminate, state)
            raise
        finally:
            self._release_reservation(owner_id)

    async def run_case(
        self,
        handle: GeneratedAgentRuntimeHandle,
        *,
        user_id: str,
        session_id: str,
        prompt: str,
    ) -> GeneratedAgentRunEvidence:
        self._require_state(handle)
        payload = {
            "app_name": handle.app_name,
            "user_id": user_id,
            "session_id": session_id,
            "new_message": {
                "role": "user",
                "parts": [{"text": prompt}] if prompt else [],
            },
            "streaming": True,
        }
        output = ""
        async for event in self.stream(handle, payload):
            error = (
                event.get("error")
                or event.get("errorMessage")
                or event.get("error_message")
            )
            if error:
                raise GeneratedAgentRuntimeError(502, str(error))
            if event.get("partial") is True:
                continue
            content = event.get("content")
            if not isinstance(content, dict):
                continue
            parts = content.get("parts")
            if not isinstance(parts, list):
                continue
            texts = [
                str(part["text"])
                for part in parts
                if isinstance(part, dict)
                and part.get("text")
                and part.get("thought") is not True
            ]
            if texts:
                output = "\n".join(texts)
        trace = await self.trace(handle, session_id=session_id)
        return GeneratedAgentRunEvidence(
            output=output,
            trace_ref=(
                f"generated-agent-runtime://{handle.runtime_id}/trace/{session_id}"
            ),
            trace=trace,
        )

    async def create_session(
        self,
        handle: GeneratedAgentRuntimeHandle,
        *,
        user_id: str,
    ) -> str:
        state = self._require_state(handle)
        url = (
            f"{state.base_url}/apps/{quote(handle.app_name, safe='')}/users/"
            f"{quote(user_id, safe='')}/sessions"
        )
        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                response = await client.post(url, json={})
        except httpx.HTTPError as error:
            raise GeneratedAgentRuntimeError(
                502,
                "Unable to create a generated Agent runtime session.",
            ) from error
        if response.status_code >= 400:
            raise GeneratedAgentRuntimeError(
                response.status_code,
                self._response_error_detail(
                    state,
                    "Generated Agent runtime session request failed",
                    response.status_code,
                    response.text,
                ),
            )
        try:
            value = response.json()
        except ValueError as error:
            raise GeneratedAgentRuntimeError(
                502,
                "Generated Agent runtime session response is invalid.",
            ) from error
        session_id = value.get("id") if isinstance(value, dict) else None
        if not isinstance(session_id, str) or not session_id:
            raise GeneratedAgentRuntimeError(
                502,
                "Generated Agent runtime session response is invalid.",
            )
        return session_id

    async def stream(
        self,
        handle: GeneratedAgentRuntimeHandle,
        payload: Mapping[str, Any],
    ):
        state = self._require_state(handle)
        request_payload = dict(payload)
        request_payload["app_name"] = handle.app_name
        try:
            async with asyncio.timeout(self._stream_timeout_seconds):
                async with httpx.AsyncClient(timeout=None) as client:
                    async with client.stream(
                        "POST",
                        f"{state.base_url}/run_sse",
                        json=request_payload,
                        timeout=None,
                    ) as response:
                        if response.status_code >= 400:
                            body = (await response.aread()).decode("utf-8", "replace")
                            raise GeneratedAgentRuntimeError(
                                response.status_code,
                                self._response_error_detail(
                                    state,
                                    "Generated Agent runtime request failed",
                                    response.status_code,
                                    body,
                                ),
                            )
                        async for event in _parse_sse(response.aiter_bytes()):
                            yield event
        except asyncio.CancelledError:
            raise
        except GeneratedAgentRuntimeError:
            raise
        except TimeoutError as error:
            raise GeneratedAgentRuntimeError(
                504,
                "Generated Agent runtime request timed out.",
            ) from error
        except httpx.HTTPError as error:
            raise GeneratedAgentRuntimeError(
                502,
                "Unable to connect to the generated Agent runtime.",
            ) from error

    async def trace(
        self,
        handle: GeneratedAgentRuntimeHandle,
        *,
        session_id: str,
    ) -> tuple[dict[str, Any], ...]:
        state = self._require_state(handle)
        url = (
            f"{state.base_url}/dev/apps/{quote(handle.app_name, safe='')}"
            f"/debug/trace/session/{quote(session_id, safe='')}"
        )
        try:
            async with httpx.AsyncClient(timeout=15.0) as client:
                response = await client.get(url)
        except httpx.HTTPError as error:
            raise GeneratedAgentRuntimeError(
                502,
                "Unable to load the generated Agent runtime trace.",
            ) from error
        if response.status_code >= 400:
            raise GeneratedAgentRuntimeError(
                response.status_code,
                self._response_error_detail(
                    state,
                    "Generated Agent runtime trace request failed",
                    response.status_code,
                    response.text,
                ),
            )
        try:
            value = response.json()
        except ValueError as error:
            raise GeneratedAgentRuntimeError(
                502,
                "Generated Agent runtime trace response is invalid.",
            ) from error
        if not isinstance(value, list) or not all(
            isinstance(item, dict) for item in value
        ):
            raise GeneratedAgentRuntimeError(
                502,
                "Generated Agent runtime trace response is invalid.",
            )
        return tuple(dict(item) for item in value)

    async def close(self, handle: GeneratedAgentRuntimeHandle) -> None:
        with self._lock:
            state = self._states.pop(handle.runtime_id, None)
        if state is not None:
            await asyncio.to_thread(self._terminate, state)

    def require_access(
        self,
        runtime_id: str,
        *,
        owner_id: str,
        is_admin: bool,
    ) -> GeneratedAgentRuntimeHandle:
        self.cleanup_expired()
        with self._lock:
            state = self._states.get(runtime_id)
        if state is None or (not is_admin and state.owner_id != owner_id):
            raise GeneratedAgentRuntimeError(404, "Generated Agent runtime not found.")
        return state.handle

    def base_url(self, handle: GeneratedAgentRuntimeHandle) -> str:
        """Return the loopback endpoint for an owned runtime handle."""

        return self._require_state(handle).base_url

    def cleanup_expired(self) -> None:
        now = self._clock()
        expired: list[_RuntimeState] = []
        with self._lock:
            for runtime_id, state in list(self._states.items()):
                if state.expires_at <= now or state.process.poll() is not None:
                    expired.append(self._states.pop(runtime_id))
        for state in expired:
            self._terminate(state)

    def close_all(self) -> None:
        with self._lock:
            states = list(self._states.values())
            self._states.clear()
        for state in states:
            self._terminate(state)

    def _launch(
        self,
        project: GeneratedProject,
        environment: dict[str, str],
        owner_id: str,
        plan_hash: str,
    ) -> _RuntimeState:
        temp_dir = tempfile.mkdtemp(prefix="veadk_generated_agent_test_")
        process: subprocess.Popen[Any] | None = None
        try:
            app_name = _write_generated_project(project, temp_dir)
            port = _free_local_port()
            base_url = f"http://127.0.0.1:{port}"
            stdout_path = Path(temp_dir) / "runner.stdout.log"
            stderr_path = Path(temp_dir) / "runner.stderr.log"
            command = [
                sys.executable,
                "-m",
                "veadk.cli.generated_agent_test_runner",
                "--agents-dir",
                str(Path(temp_dir) / "agents"),
                "--host",
                "127.0.0.1",
                "--port",
                str(port),
            ]
            with stdout_path.open("w", encoding="utf-8") as stdout_file:
                with stderr_path.open("w", encoding="utf-8") as stderr_file:
                    process_environment = {
                        **environment,
                        "HOME": temp_dir,
                        "TMPDIR": temp_dir,
                        "TEMP": temp_dir,
                        "TMP": temp_dir,
                    }
                    process = subprocess.Popen(
                        command,
                        cwd=temp_dir,
                        env=process_environment,
                        stdout=stdout_file,
                        stderr=stderr_file,
                    )
            expires_at = self._clock() + self._ttl_seconds
            handle = GeneratedAgentRuntimeHandle(
                runtime_id=self._id_factory(),
                app_name=app_name,
                expires_at=expires_at,
                plan_hash=plan_hash,
            )
            return _RuntimeState(
                handle=handle,
                temp_dir=temp_dir,
                base_url=base_url,
                process=process,
                expires_at=expires_at,
                owner_id=owner_id,
            )
        except BaseException:
            if process is not None:
                process.terminate()
                try:
                    process.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=3)
            shutil.rmtree(temp_dir, ignore_errors=True)
            raise

    async def _wait_until_ready(self, state: _RuntimeState) -> None:
        deadline = time.monotonic() + self._ready_timeout_seconds
        last_error = ""
        async with httpx.AsyncClient(timeout=2.0) as client:
            while time.monotonic() < deadline:
                if state.process.poll() is not None:
                    raise GeneratedAgentRuntimeError(
                        400,
                        self._log_detail(
                            state,
                            "Generated Agent runtime exited before becoming ready.",
                        ),
                    )
                try:
                    response = await client.get(f"{state.base_url}/list-apps")
                    if response.status_code == 200 and state.handle.app_name in (
                        response.json() or []
                    ):
                        return
                    last_error = f"list-apps returned {response.status_code}"
                except Exception as error:  # noqa: BLE001 - retry readiness probe
                    last_error = str(error)
                remaining = max(0.0, deadline - time.monotonic())
                await asyncio.sleep(min(0.25, remaining))
        raise GeneratedAgentRuntimeError(
            504,
            self._log_detail(
                state,
                "Generated Agent runtime did not become ready"
                + (f": {last_error}" if last_error else "."),
            ),
        )

    def _require_state(
        self,
        handle: GeneratedAgentRuntimeHandle,
    ) -> _RuntimeState:
        self.cleanup_expired()
        with self._lock:
            state = self._states.get(handle.runtime_id)
        if state is None or state.handle != handle:
            raise GeneratedAgentRuntimeError(404, "Generated Agent runtime not found.")
        return state

    def _reserve(self, owner_id: str) -> None:
        with self._lock:
            active = sum(
                state.owner_id == owner_id for state in self._states.values()
            ) + self._creating.get(owner_id, 0)
            if active >= self._max_active_per_owner:
                raise GeneratedAgentRuntimeError(
                    429,
                    "Generated Agent runtime concurrency limit reached.",
                )
            self._creating[owner_id] = self._creating.get(owner_id, 0) + 1

    def _release_reservation(self, owner_id: str) -> None:
        with self._lock:
            remaining = max(0, self._creating.get(owner_id, 0) - 1)
            if remaining:
                self._creating[owner_id] = remaining
            else:
                self._creating.pop(owner_id, None)

    def _log_detail(self, state: _RuntimeState, prefix: str) -> str:
        parts = [prefix]
        base = Path(state.temp_dir)
        for label, path in (
            ("stderr", base / "runner.stderr.log"),
            ("stdout", base / "runner.stdout.log"),
        ):
            content = _read_log_tail(path)
            if content:
                redacted = self._redact(content)
                if redacted:
                    parts.append(f"{label}:\n{redacted}")
        if len(parts) == 1:
            parts.append("No runner logs were captured.")
        return "\n\n".join(parts)

    def _response_error_detail(
        self,
        state: _RuntimeState,
        operation: str,
        status_code: int,
        response_text: str,
    ) -> str:
        response_detail = self._redact(response_text.strip())
        prefix = f"{operation} (HTTP {status_code})"
        if response_detail and response_detail.lower() != "internal server error":
            prefix += f"\nResponse: {response_detail[:2000]}"
        return self._log_detail(state, prefix)

    @staticmethod
    def _terminate(state: _RuntimeState) -> None:
        if state.process.poll() is None:
            state.process.terminate()
            try:
                state.process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                state.process.kill()
                state.process.wait(timeout=3)
        shutil.rmtree(state.temp_dir, ignore_errors=True)


def validate_generated_project(project: GeneratedProject) -> str:
    """Validate a generated project before persisting or materializing it."""
    if not project.name:
        raise GeneratedAgentRuntimeError(400, "Agent name is required.")
    if not project.files:
        raise GeneratedAgentRuntimeError(400, "Generated project has no files.")
    if len(project.files) > _MAX_FILES:
        raise GeneratedAgentRuntimeError(400, "Generated project has too many files.")

    total_bytes = 0
    paths: set[str] = set()
    applications: set[str] = set()
    for item in project.files:
        path_value = item.path
        encoded = item.content.encode("utf-8")
        if len(encoded) > _MAX_FILE_BYTES:
            raise GeneratedAgentRuntimeError(400, f"File is too large: {path_value}")
        total_bytes += len(encoded)
        if total_bytes > _MAX_TOTAL_BYTES:
            raise GeneratedAgentRuntimeError(400, "Generated project is too large.")
        path = Path(path_value)
        if (
            path.is_absolute()
            or "\x00" in path_value
            or any(part in {"", ".", ".."} for part in path.parts)
        ):
            raise GeneratedAgentRuntimeError(400, f"Illegal file path: {path_value}")
        normalized_path = path.as_posix()
        if normalized_path in paths:
            raise GeneratedAgentRuntimeError(
                400,
                f"Duplicate file path: {path_value}",
            )
        paths.add(normalized_path)
        if (
            len(path.parts) == 3
            and path.parts[0] == "agents"
            and path.parts[2] == "agent.py"
        ):
            applications.add(path.parts[1])

    if project.name in applications:
        return project.name
    if len(applications) == 1:
        return next(iter(applications))
    raise GeneratedAgentRuntimeError(
        400,
        "Generated project must contain exactly one agents/<name>/agent.py.",
    )


def _write_generated_project(project: GeneratedProject, temp_dir: str) -> str:
    app_name = validate_generated_project(project)
    base = Path(temp_dir).resolve()
    for item in project.files:
        destination = (base / Path(item.path)).resolve()
        if not destination.is_relative_to(base):
            raise GeneratedAgentRuntimeError(400, f"Illegal file path: {item.path}")
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(item.content, encoding="utf-8")
    agents_dir = base / "agents"
    try:
        conflicts = importlib.util.find_spec(app_name) is not None
    except (ImportError, AttributeError, ValueError):
        conflicts = app_name in sys.modules
    if conflicts:
        debug_name = f"veadk_debug_{app_name}"
        (agents_dir / app_name).rename(agents_dir / debug_name)
        return debug_name
    return app_name


def _read_log_tail(path: Path, max_chars: int = 6000) -> str:
    try:
        with path.open("rb") as file:
            file.seek(0, 2)
            size = file.tell()
            file.seek(max(0, size - max_chars * 4))
            text = file.read().decode("utf-8", "replace")
    except OSError:
        return ""
    return text[-max_chars:].strip()


async def _parse_sse(chunks: Any):
    buffer = ""
    decoder = codecs.getincrementaldecoder("utf-8")("replace")
    async for chunk in chunks:
        buffer += decoder.decode(chunk)
        while True:
            newline = buffer.find("\n\n")
            carriage = buffer.find("\r\n\r\n")
            positions = [value for value in (newline, carriage) if value >= 0]
            if not positions:
                break
            position = min(positions)
            separator_length = 4 if buffer.startswith("\r\n\r\n", position) else 2
            frame = buffer[:position]
            buffer = buffer[position + separator_length :]
            data = "\n".join(
                line[5:].lstrip()
                for line in frame.splitlines()
                if line.startswith("data:")
            )
            if not data or data in {"[DONE]", "ping"}:
                continue
            try:
                value = json.loads(data)
            except json.JSONDecodeError:
                continue
            if isinstance(value, dict):
                yield value
