# Copyright (c) 2025 Beijing Volcano Engine Technology Co., Ltd. and/or its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os

from veadk import Agent
from veadk.memory.short_term_memory import ShortTermMemory
from veadk.tools.demo_tools import get_city_weather
from veadk.tracing.base_tracer import BaseTracer
from veadk.tracing.telemetry.opentelemetry_tracer import OpentelemetryTracer

# =============
# Generated by VeADK, do not edit!!!
# =============
TRACERS: list[BaseTracer] = []

exporters = []
if os.getenv("VEADK_TRACER_APMPLUS", "").lower() == "true":
    from veadk.tracing.telemetry.exporters.apmplus_exporter import APMPlusExporter

    exporters.append(APMPlusExporter())

if os.getenv("VEADK_TRACER_COZELOOP", "").lower() == "true":
    from veadk.tracing.telemetry.exporters.cozeloop_exporter import CozeloopExporter

    exporters.append(CozeloopExporter())

if os.getenv("VEADK_TRACER_TLS", "").lower() == "true":
    from veadk.tracing.telemetry.exporters.tls_exporter import TLSExporter

    exporters.append(TLSExporter())

TRACERS.append(OpentelemetryTracer(exporters=exporters))

# =============
# Required [you can edit here]
# =============
APP_NAME: str = "weather-reporter"  # <--- export your app name
AGENT: Agent = Agent(tools=[get_city_weather])  # <--- export your agent
SHORT_TERM_MEMORY: ShortTermMemory = (
    ShortTermMemory()
)  # <--- export your short term memory

# =============
# Optional
# =============
# Other global variables
