name: License Header Check

on:   
  push:
  pull_request:

  workflow_dispatch:

jobs:
  License-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.4.0
